import Foundation

/// Generates Project.swift content for Tuist
struct ProjectWriter {

    /// Generate Project.swift content for a Tuist project
    func generate(project: TuistProject) -> String {
        var output = """
        // Generated by PackageToTuistProject
        import ProjectDescription

        let project = Project(
            name: "\(project.name)",
            options: .options(
                disableSynthesizedResourceAccessors: true
            ),
            targets: [

        """

        for (index, target) in project.targets.enumerated() {
            let targetCode = generateTarget(target)
            output += targetCode
            if index < project.targets.count - 1 {
                output += ","
            }
            output += "\n"
        }

        output += """
            ]
        )
        """

        return output
    }

    private func generateTarget(_ target: TuistTarget) -> String {
        var code = """
                .target(
                    name: "\(target.name)",
                    destinations: \(target.destinations),
                    product: \(target.product.swiftCode),
                    bundleId: "\(target.bundleId)",
        """

        if let deploymentTargets = target.deploymentTargets {
            code += "\n            deploymentTargets: \(deploymentTargets),"
        }

        code += "\n            sources: [\"\(target.sourcesPath)/**\"],"
        code += "\n            resources: [\"\(target.sourcesPath)/Resources/**\"]"

        if !target.dependencies.isEmpty {
            code += ",\n            dependencies: [\n"
            for (index, dep) in target.dependencies.enumerated() {
                code += "                \(dep.swiftCode)"
                if index < target.dependencies.count - 1 {
                    code += ","
                }
                code += "\n"
            }
            code += "            ]"
        }

        // Add settings with -package-name flag for package access level support
        // and STRING_CATALOG_GENERATE_SYMBOLS which is the default for Swift packages
        var settingsPairs: [String] = [
            "\"OTHER_SWIFT_FLAGS\": [\"-package-name\", \"\(target.packageName)\"]",
            "\"STRING_CATALOG_GENERATE_SYMBOLS\": \"YES\"",
            "\"SWIFT_PACKAGE_NAME\": \"\(target.packageName)\"",
            "\"SWIFT_ACTIVE_COMPILATION_CONDITIONS\": \"$(inherited) SWIFT_PACKAGE\""
        ]
        if target.needsTestingSearchPaths {
            settingsPairs.append("\"ENABLE_TESTING_SEARCH_PATHS\": \"YES\"")
        }
        code += ",\n            settings: .settings(base: [\(settingsPairs.joined(separator: ", "))])"

        code += "\n        )"

        return code
    }

    /// Write Project.swift to disk
    func write(project: TuistProject, dryRun: Bool, verbose: Bool) throws {
        let content = generate(project: project)
        let projectDir = URL(fileURLWithPath: project.path)
        let outputPath = projectDir.appendingPathComponent("Project.swift")

        if dryRun {
            print("\n--- Would write to: \(outputPath.path) ---")
            print(content)
            print("--- End ---\n")
        } else {
            try content.write(to: outputPath, atomically: true, encoding: .utf8)
            if verbose {
                print("Wrote: \(outputPath.path)")
            }
        }
    }
}
